// Copyright (c) Serendipity Project Contributors
// Licensed under the terms of the MIT license.

Module ::= ListContents

<ListContents> ::= Expression (<Split> Expression)*
BracketList ::= '[' ws-opt ListContents? ws-opt ']'
ParenList ::= '(' ws-opt ListContents? ws-opt ')'
BraceList ::= '{' ws-opt ListContents? ws-opt '}'

ListRest ::= (Sigil ListRest) | (ws-req ListRest);

Expression ::= 
  | '#' Set
  | Tuple
  | Array
  | Map
  | <Atom>

Atom ::= Number | String | Symbol | Sigil

// (foo, "bar", "ba" + "z", qux(value))
Tuple ::= <ParenList>
Array ::= <BracketList>

// Map literals are like object literals in JS, but using fat arrows
n
// {
//   sym => "foo",
//   0 => "ba" + "r",
//   "str" => "baz",
//   [computed + "key"] => "qux",
//   ...rest
// }
Map ::= '{' MapInterior? '}'
MapInterior ::= KeyValuePair (',' KeyValuePair)* (',' MapConjunction)? ','?
MapElement ::=
KeyValuePair ::= MapKey '=>' MapValue
MapKey ::= Atom | BracketList
MapValue ::= Expression+
MapConjunction ::= '...' MapValue

// #{this, that, the(other).thing}
Set ::= <BraceList>

// +0
// -0
// -5
// +0x1A
Number ::= /[+-]?[0-9]([bqodx][0-9a-fA-F])?[0-9a-fA-F]*(\.[0-9a-fA-F]+)?/

String ::=
  | '"' /([^"\n]|\\"|\\\n)*/ '"'
  | '\'' /([^'\n]|\\'|\\\n)*/ '\''

Sigil ::= /[,.:;<>?|!@#$%^&*-=+]+/

Symbol ::= /[^\s<Sigil>]+/

Comment ::= /\/\/[^\n]*/

BlockComment ::= '/*' InsideBlockComment '*/'
InsideBlockComment ::=
  | /[^\*]/ InsideBlockComment
  | /\*[^\/]/ InsideBlockComment

Whitespace ::= /\s+/ | Comment | BlockComment

ws-req ::= Whitespace+
ws-opt ::= Whitespace*